### ISSUE TITLE
运行loppo报错

### ISSUE THREAD

**Issue by olivercm** [ruanyf/loppo#16]
/usr/local/lib/node_modules/loppo/node_modules/tarim/index.js:17
    );
    ^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/loppo/lib/theme.js:8:20)
    at Module._compile (module.js:571:32)

**Comment by ruanyf** [comment]
升级一下 Node。

**Comment by orangeyts** [comment]
C:\Users\hehe\AppData\Roaming\npm\node_modules\loppo\node_modules\_tarim@0.1.1@tarim\index.js:17
    );
    ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\hehe\AppData\Roaming\npm\node_modules\loppo\lib\theme.js:8:20)

D:\hs\document\my\oschina\microservice\spring-Microservices-in-action>node -v
v6.11.4

windows最新版本了，还是不行

**Comment by ruanyf** [comment]
我看一下，能不能让 6.x 可以运行。

**Comment by ruanyf** [comment]
你把 node_modules 目录删除，重装一下依赖。

我发了一个新版本，应该可以了。

**Comment by orangeyts** [comment]
谢谢，升级到v8.7.0 可以了

**Comment by ruanyf** [comment]
源码里面，函数的尾参数后面加了逗号，导致老版本的 Node 不支持。

现在已经改掉了。
