### ISSUE TITLE
$ loppo 报错

### ISSUE THREAD

**Issue by TongchengQiu** [ruanyf/loppo#4]
```bash
$ loppo-demo loppo
/usr/local/lib/node_modules/loppo/bin/cmd.js:57
if (!argv._.includes('server') && !argv._.includes('count')) {
            ^

TypeError: argv._.includes is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/loppo/bin/cmd.js:57:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
```

node: v4.6.0
npm: v4.1.1

**Comment by ruanyf** [comment]
源码用了`Array.prototype.includes()`，需要 Node 6。

你升级一下 Node 吧。

**Comment by ruanyf** [comment]
改掉了，你安装最新的 v0.4.5，应该不用升级 Node 了。
