### ISSUE TITLE
运行loppo报错：/usr/local/lib/node_modules/loppo/node_modules/markdown-it/lib/renderer.js:108   return options.breaks ? (options.xhtmlOut ? '<br />\n' : '<br>\n') : '\n';                 ^

### ISSUE THREAD

**Issue by chayangge** [ruanyf/loppo#5]
具体错误：

➜  myloppo loppo
✔ INFO [19:29:32] - [BEGIN] build docs
✔ INFO [19:29:32] - [BEGIN] handle config file
ℹ INFO [19:29:32] - [INFO] create the config file
✔ INFO [19:29:32] - [END] handle config file
✔ INFO [19:29:32] - [BEGIN] handle chapters file
ℹ INFO [19:29:32] - [INFO] create the chapters file
✔ INFO [19:29:32] - [END] handle chapters file
✔ INFO [19:29:32] - [BEGIN] handle theme files
✔ INFO [19:29:32] - [END] handle theme files
✔ INFO [19:29:32] - [BEGIN] copy assets to output directory
✔ INFO [19:29:32] - [END] copy assets to output directory
✔ INFO [19:29:32] - [BEGIN] publish pages to output directory
✔ INFO [19:29:32] - [BEGIN] create / page
✔ INFO [19:29:32] - [END] create / page
✔ INFO [19:29:32] - [BEGIN] create a.md page
/usr/local/lib/node_modules/loppo/node_modules/markdown-it/lib/renderer.js:108
  return options.breaks ? (options.xhtmlOut ? '<br />\n' : '<br>\n') : '\n';
                ^

TypeError: Cannot read property 'breaks' of undefined
    at Object.default_rules.softbreak (/usr/local/lib/node_modules/loppo/node_modules/markdown-it/lib/renderer.js:108:17)
    at Renderer.renderInline (/usr/local/lib/node_modules/loppo/node_modules/markdown-it/lib/renderer.js:271:28)
    at Renderer.render (/usr/local/lib/node_modules/loppo/node_modules/markdown-it/lib/renderer.js:324:22)
    at Array.<anonymous> (/usr/local/lib/node_modules/loppo/node_modules/markdown-it-toc-and-anchor/dist/index.js:85:49)
    at Core.process (/usr/local/lib/node_modules/loppo/node_modules/markdown-it/lib/parser_core.js:51:13)
    at MarkdownIt.parse (/usr/local/lib/node_modules/loppo/node_modules/markdown-it/lib/index.js:519:13)
    at MarkdownIt.render (/usr/local/lib/node_modules/loppo/node_modules/markdown-it/lib/index.js:539:36)
    at markdownRender (/usr/local/lib/node_modules/loppo/lib/utils.js:552:26)
    at makePage (/usr/local/lib/node_modules/loppo/lib/utils.js:640:15)
    at /usr/local/lib/node_modules/loppo/lib/page.js:13:5

**Comment by chayangge** [comment]
问题已解决，原因：
直接从hexo项目中拷贝过来的markdown文件，开头格式有问题
title: 点击统计
date: 2016-07-12 11:00:19
tags: javascript
--- （就是这三条线引发的）

解决方法： 敲个回车就行（或其他操作），只要打乱原有位置就行，其余位置的---也都能正常解析为横线，好奇怪
